version: '3' #docker version
services:
  www:
    depends_on:
      - db
    image: php:7.2-apache
    volumes:
      - "./:/var/www/html" #sync project dir with container web dir
    ports:
      - 80:80
      - 433:433 # for future ssl trafic
    networks:
      - myapp  
  db:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: myapp
      MYSQL_USER: myapp
      MYSQL_PASSWORD: password
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    # volumes:
    #   - "./db:/docker-entrypoint-initdb.d"
    networks:
      - myapp  
  phpmyadmin:
    image: phpmyadmin
    ports:
      - 8081:80
    environment:
      - PMA_HOST:db
      - PMA_PORT:3306
    networks:
      - myapp    
networks:
  myapp:
    driver: bridge     